services:
  app:
    build: .
    container_name: "shop"
    env_file:
      - .env
    ports:
      - 8181:8181
    networks:
      - shop_ntwrk  
    environment:
      - TZ=Asia/Tashkent
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
  minio:
    image: minio/minio
    container_name: shop_minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    ports:
      - "9002:9002"   
      - "9003:9003" 
    command: server /data --address ":9002" --console-address ":9003"
    volumes:
      - minio_data:/data
    networks:
      - shop_ntwrk
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: shop
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_ntwrk
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command: >
      sleep 5 &&
      migrate -path=/migrations -database=${PG_URL} up
    environment:
      - DATABASE_URL=${PG_URL}

networks:
  shop_ntwrk: 
    external: true


volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
